# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0096_auto_20180626_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='state',
            field=models.CharField(choices=[('created', 'created'), ('pending', 'pending'), ('confirmed', 'confirmed'), ('canceled', 'canceled'), ('failed', 'failed'), ('refunded', 'refunded')], max_length=190),
        ),
    ]
