# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 12:57
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0097_auto_20180626_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderpayment',
            options={'ordering': ('created',)},
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pretixbase.OrderFee'),
        ),
    ]
