# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 12:41
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0098_auto_20180628_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrefund',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='pretixbase.OrderPayment'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pretixbase.OrderFee'),
        ),
        migrations.AlterField(
            model_name='orderrefund',
            name='state',
            field=models.CharField(choices=[('requested', 'requested'), ('approved', 'approved'), ('external', 'processed externally'), ('created', 'created'), ('transit', 'in transit'), ('done', 'done'), ('rejected', 'rejected'), ('canceled', 'canceled')], max_length=190),
        ),
    ]
