# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0099_auto_20180703_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='local_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderrefund',
            name='local_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderrefund',
            name='state',
            field=models.CharField(choices=[('external', 'started externally'), ('created', 'created'), ('transit', 'in transit'), ('done', 'done'), ('failed', 'failed'), ('canceled', 'canceled')], max_length=190),
        ),
    ]
